/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const EquipmentItem = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'brand' : IDL.Text,
  'currentStock' : IDL.Nat,
  'rackNumber' : IDL.Text,
  'openingStock' : IDL.Nat,
});
export const Staff = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'mobile' : IDL.Text,
});
export const AttendanceEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'staffId' : IDL.Nat,
  'date' : IDL.Text,
});
export const CashEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'recipientStaffId' : IDL.Nat,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const EquipmentCheckout = IDL.Record({
  'id' : IDL.Nat,
  'staffId' : IDL.Nat,
  'date' : IDL.Text,
  'takenAt' : IDL.Text,
  'equipmentId' : IDL.Nat,
  'returnedAt' : IDL.Text,
});
export const HomeServiceSettlement = IDL.Record({
  'id' : IDL.Nat,
  'staffId' : IDL.Nat,
  'clientName' : IDL.Text,
  'clientPaid' : IDL.Nat,
  'date' : IDL.Text,
  'serviceAmount' : IDL.Nat,
  'notes' : IDL.Text,
  'travelExpense' : IDL.Nat,
});
export const UsageRecord = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'staffId' : IDL.Nat,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCashEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addCategory' : IDL.Func([IDL.Text], [Category], []),
  'addEquipmentCheckout' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addEquipmentItem' : IDL.Func([IDL.Text], [EquipmentItem], []),
  'addHomeServiceSettlement' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [Product],
      [],
    ),
  'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Staff], []),
  'addUsageRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'clearAttendance' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteCashEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteEquipmentItem' : IDL.Func([IDL.Nat], [], []),
  'deleteHomeServiceSettlement' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteStaff' : IDL.Func([IDL.Nat], [], []),
  'deleteUsageRecord' : IDL.Func([IDL.Nat], [], []),
  'getAttendanceEntries' : IDL.Func([], [IDL.Vec(AttendanceEntry)], ['query']),
  'getCashEntries' : IDL.Func([], [IDL.Vec(CashEntry)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getEquipmentCheckouts' : IDL.Func(
      [],
      [IDL.Vec(EquipmentCheckout)],
      ['query'],
    ),
  'getEquipmentItems' : IDL.Func([], [IDL.Vec(EquipmentItem)], ['query']),
  'getHomeServiceSettlements' : IDL.Func(
      [],
      [IDL.Vec(HomeServiceSettlement)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getUsageRecords' : IDL.Func([], [IDL.Vec(UsageRecord)], ['query']),
  'markAllPresent' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [], []),
  'returnEquipmentCheckout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setAttendance' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateStaff' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const EquipmentItem = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'brand' : IDL.Text,
    'currentStock' : IDL.Nat,
    'rackNumber' : IDL.Text,
    'openingStock' : IDL.Nat,
  });
  const Staff = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const AttendanceEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'staffId' : IDL.Nat,
    'date' : IDL.Text,
  });
  const CashEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'recipientStaffId' : IDL.Nat,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const EquipmentCheckout = IDL.Record({
    'id' : IDL.Nat,
    'staffId' : IDL.Nat,
    'date' : IDL.Text,
    'takenAt' : IDL.Text,
    'equipmentId' : IDL.Nat,
    'returnedAt' : IDL.Text,
  });
  const HomeServiceSettlement = IDL.Record({
    'id' : IDL.Nat,
    'staffId' : IDL.Nat,
    'clientName' : IDL.Text,
    'clientPaid' : IDL.Nat,
    'date' : IDL.Text,
    'serviceAmount' : IDL.Nat,
    'notes' : IDL.Text,
    'travelExpense' : IDL.Nat,
  });
  const UsageRecord = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'staffId' : IDL.Nat,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCashEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addCategory' : IDL.Func([IDL.Text], [Category], []),
    'addEquipmentCheckout' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addEquipmentItem' : IDL.Func([IDL.Text], [EquipmentItem], []),
    'addHomeServiceSettlement' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [Product],
        [],
      ),
    'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Staff], []),
    'addUsageRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'clearAttendance' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteCashEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteEquipmentItem' : IDL.Func([IDL.Nat], [], []),
    'deleteHomeServiceSettlement' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteStaff' : IDL.Func([IDL.Nat], [], []),
    'deleteUsageRecord' : IDL.Func([IDL.Nat], [], []),
    'getAttendanceEntries' : IDL.Func(
        [],
        [IDL.Vec(AttendanceEntry)],
        ['query'],
      ),
    'getCashEntries' : IDL.Func([], [IDL.Vec(CashEntry)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getEquipmentCheckouts' : IDL.Func(
        [],
        [IDL.Vec(EquipmentCheckout)],
        ['query'],
      ),
    'getEquipmentItems' : IDL.Func([], [IDL.Vec(EquipmentItem)], ['query']),
    'getHomeServiceSettlements' : IDL.Func(
        [],
        [IDL.Vec(HomeServiceSettlement)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getUsageRecords' : IDL.Func([], [IDL.Vec(UsageRecord)], ['query']),
    'markAllPresent' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [], []),
    'returnEquipmentCheckout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setAttendance' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateStaff' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };