/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'brand' : IDL.Text,
  'currentStock' : IDL.Nat,
  'openingStock' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text], [Category], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [Product],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'brand' : IDL.Text,
    'currentStock' : IDL.Nat,
    'openingStock' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text], [Category], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [Product],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };