/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'lowStockThreshold' : bigint,
  'name' : string,
  'unit' : string,
  'brand' : string,
  'currentStock' : bigint,
  'openingStock' : bigint,
}
export interface Staff { 'id' : bigint, 'name' : string, 'role' : string }
export interface UsageRecord {
  'id' : bigint,
  'categoryId' : bigint,
  'staffId' : bigint,
  'clientName' : string,
  'date' : string,
  'time' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[string], Category>,
  'addProduct' : ActorMethod<[string, bigint, bigint, string, bigint], Product>,
  'addStaff' : ActorMethod<[string, string], Staff>,
  'addUsageRecord' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, string, string],
    UsageRecord
  >,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteStaff' : ActorMethod<[bigint], boolean>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getUsageRecords' : ActorMethod<[], Array<UsageRecord>>,
  'getUsageStats' : ActorMethod<
    [],
    { 'totalUsageAllTime' : bigint, 'totalUsageToday' : bigint }
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, bigint, string, bigint],
    [] | [Product]
  >,
  'updateStaff' : ActorMethod<[bigint, string, string], [] | [Staff]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];