/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EquipmentItem {
    id: bigint;
    name: string;
}
export interface Category {
    id: bigint;
    name: string;
}
export interface HomeServiceSettlement {
    id: bigint;
    staffId: bigint;
    clientName: string;
    clientPaid: bigint;
    date: string;
    serviceAmount: bigint;
    notes: string;
    travelExpense: bigint;
}
export interface CashEntry {
    id: bigint;
    entryType: string;
    date: string;
    description: string;
    recipientStaffId: bigint;
    notes: string;
    amount: bigint;
}
export interface PackDistribution {
    id: bigint;
    staffId: bigint;
    date: string;
    time: string;
    notes: string;
    quantity: bigint;
    packItemId: bigint;
}
export interface UsageRecord {
    id: bigint;
    categoryId: bigint;
    staffId: bigint;
    clientName: string;
    date: string;
    time: string;
    productId: bigint;
    quantity: bigint;
}
export interface PackArrival {
    id: bigint;
    date: string;
    notes: string;
    quantity: bigint;
    packItemId: bigint;
}
export interface Staff {
    id: bigint;
    name: string;
    role: string;
    pinned: boolean;
    mobile: string;
}
export interface EquipmentCheckout {
    id: bigint;
    staffId: bigint;
    date: string;
    takenAt: string;
    equipmentId: bigint;
    returnedAt: string;
}
export interface AttendanceEntry {
    id: bigint;
    status: string;
    staffId: bigint;
    date: string;
}
export interface PackItem {
    id: bigint;
    name: string;
    unit: string;
}
export interface Product {
    id: bigint;
    categoryId: bigint;
    lowStockThreshold: bigint;
    name: string;
    unit: string;
    openingDate: string;
    brand: string;
    currentStock: bigint;
    rackNumber: string;
    openingStock: bigint;
}
export interface backendInterface {
    addCashEntry(date: string, entryType: string, amount: bigint, description: string, recipientStaffId: bigint, notes: string): Promise<CashEntry>;
    addCategory(name: string): Promise<Category>;
    addEquipmentCheckout(staffId: bigint, equipmentId: bigint, date: string, takenAt: string): Promise<EquipmentCheckout>;
    addEquipmentItem(name: string): Promise<EquipmentItem>;
    addHomeServiceSettlement(date: string, staffId: bigint, clientName: string, serviceAmount: bigint, clientPaid: bigint, travelExpense: bigint, notes: string): Promise<HomeServiceSettlement>;
    addPackArrival(packItemId: bigint, date: string, quantity: bigint, notes: string): Promise<PackArrival>;
    addPackDistribution(packItemId: bigint, date: string, time: string, staffId: bigint, quantity: bigint, notes: string): Promise<PackDistribution>;
    addPackItem(name: string, unit: string): Promise<PackItem>;
    addProduct(name: string, categoryId: bigint, openingStock: bigint, openingDate: string, unit: string, lowStockThreshold: bigint, rackNumber: string): Promise<Product>;
    addStaff(name: string, role: string, mobile: string): Promise<Staff>;
    addUsageRecord(date: string, productId: bigint, categoryId: bigint, staffId: bigint, quantity: bigint, time: string, clientName: string): Promise<UsageRecord>;
    bulkAddStaff(names: Array<string>, role: string): Promise<Array<Staff>>;
    clearAttendance(date: string, staffId: bigint): Promise<void>;
    deleteAllProducts(): Promise<void>;
    deleteAllStaff(): Promise<void>;
    deleteCashEntry(id: bigint): Promise<void>;
    deleteCategory(id: bigint): Promise<void>;
    deleteEquipmentItem(id: bigint): Promise<void>;
    deleteHomeServiceSettlement(id: bigint): Promise<void>;
    deletePackArrival(id: bigint): Promise<void>;
    deletePackDistribution(id: bigint): Promise<void>;
    deletePackItem(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    deleteStaff(id: bigint): Promise<void>;
    deleteUsageRecord(id: bigint): Promise<void>;
    getAttendanceEntries(): Promise<Array<AttendanceEntry>>;
    getCashEntries(): Promise<Array<CashEntry>>;
    getCategories(): Promise<Array<Category>>;
    getEquipmentCheckouts(): Promise<Array<EquipmentCheckout>>;
    getEquipmentItems(): Promise<Array<EquipmentItem>>;
    getHomeServiceSettlements(): Promise<Array<HomeServiceSettlement>>;
    getPackArrivals(): Promise<Array<PackArrival>>;
    getPackDistributions(): Promise<Array<PackDistribution>>;
    getPackItems(): Promise<Array<PackItem>>;
    getProducts(): Promise<Array<Product>>;
    getStaff(): Promise<Array<Staff>>;
    getUsageRecords(): Promise<Array<UsageRecord>>;
    markAllPresent(date: string, staffIds: Array<bigint>): Promise<void>;
    returnEquipmentCheckout(id: bigint, returnedAt: string): Promise<void>;
    setAttendance(date: string, staffId: bigint, status: string): Promise<AttendanceEntry>;
    updateProduct(id: bigint, name: string, categoryId: bigint, openingStock: bigint, openingDate: string, currentStock: bigint, unit: string, lowStockThreshold: bigint, rackNumber: string): Promise<void>;
    updateStaff(id: bigint, name: string, role: string, mobile: string): Promise<void>;
    updateStaffPin(id: bigint, pinned: boolean): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCashEntry(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: string): Promise<CashEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addCashEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCashEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addCategory(arg0: string): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async addEquipmentCheckout(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<EquipmentCheckout> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipmentCheckout(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipmentCheckout(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addEquipmentItem(arg0: string): Promise<EquipmentItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipmentItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipmentItem(arg0);
            return result;
        }
    }
    async addHomeServiceSettlement(arg0: string, arg1: bigint, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string): Promise<HomeServiceSettlement> {
        if (this.processError) {
            try {
                const result = await this.actor.addHomeServiceSettlement(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHomeServiceSettlement(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addPackArrival(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<PackArrival> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackArrival(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackArrival(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPackDistribution(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string): Promise<PackDistribution> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackDistribution(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackDistribution(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addPackItem(arg0: string, arg1: string): Promise<PackItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackItem(arg0, arg1);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: bigint, arg6: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStaff(arg0: string, arg1: string, arg2: string): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0, arg1, arg2);
            return result;
        }
    }
    async addUsageRecord(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<UsageRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addUsageRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUsageRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async bulkAddStaff(arg0: Array<string>, arg1: string): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddStaff(arg0, arg1);
            return result;
        }
    }
    async clearAttendance(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAttendance(arg0, arg1);
            return result;
        }
    }
    async deleteAllProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllProducts();
            return result;
        }
    }
    async deleteAllStaff(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllStaff();
            return result;
        }
    }
    async deleteCashEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCashEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCashEntry(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteEquipmentItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEquipmentItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEquipmentItem(arg0);
            return result;
        }
    }
    async deleteHomeServiceSettlement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHomeServiceSettlement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHomeServiceSettlement(arg0);
            return result;
        }
    }
    async deletePackArrival(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackArrival(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackArrival(arg0);
            return result;
        }
    }
    async deletePackDistribution(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackDistribution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackDistribution(arg0);
            return result;
        }
    }
    async deletePackItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackItem(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async deleteUsageRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUsageRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUsageRecord(arg0);
            return result;
        }
    }
    async getAttendanceEntries(): Promise<Array<AttendanceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceEntries();
            return result;
        }
    }
    async getCashEntries(): Promise<Array<CashEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashEntries();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getEquipmentCheckouts(): Promise<Array<EquipmentCheckout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentCheckouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentCheckouts();
            return result;
        }
    }
    async getEquipmentItems(): Promise<Array<EquipmentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentItems();
            return result;
        }
    }
    async getHomeServiceSettlements(): Promise<Array<HomeServiceSettlement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeServiceSettlements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeServiceSettlements();
            return result;
        }
    }
    async getPackArrivals(): Promise<Array<PackArrival>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackArrivals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackArrivals();
            return result;
        }
    }
    async getPackDistributions(): Promise<Array<PackDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackDistributions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackDistributions();
            return result;
        }
    }
    async getPackItems(): Promise<Array<PackItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackItems();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff();
            return result;
        }
    }
    async getUsageRecords(): Promise<Array<UsageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageRecords();
            return result;
        }
    }
    async markAllPresent(arg0: string, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllPresent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllPresent(arg0, arg1);
            return result;
        }
    }
    async returnEquipmentCheckout(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.returnEquipmentCheckout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnEquipmentCheckout(arg0, arg1);
            return result;
        }
    }
    async setAttendance(arg0: string, arg1: bigint, arg2: string): Promise<AttendanceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.setAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: bigint, arg6: string, arg7: bigint, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateStaff(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateStaffPin(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffPin(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
